export interface ExpedienteInterfaz
{
    identificador:number;
    actor:number;
    aforo:number;
    avance:string;
    cartera:number;
    cif:string;
    coordinador:string;
    detalle:string;
    espacio:number;
    evento:number;
    fechaFin:Date;
    fechaInicio:Date;
    hora:number;
    imagen:string;
    nombreExpediente:string;
    portal:string;
    precio:number;
    precioEntrada:number;
    separacion:string;
    titulo:string;
}
