export interface Expediente
{
identificador:string;
evento:string;
cartera:number;
espacio:number;
nombreExpediente:string;
fechaInicio:string;
fechaFin:string;
hora:number;
aforo:number;
titulo:string;
actor:number;
precio:number;
portal:string;
separacion:string;
precioEntrada:number;
coordinador:string;
cif:number;
detalle:string;
imagen:string;
avance:string;
fechaCreacion:string;
fechaActualizacion:string;
fechaEliminacion:string;
}
